### ISSUE TITLE
Point lights disappear at certain angles on headset builds.

### ISSUE THREAD

**Issue by reeseras** [provencher/MRTK-Quest-Sample#6]
I'm not sure what is causing this, whether it be Unity, MRTK, or the Oculus Quest 2 itself, but I can't seem to find a solution for it. On PC it runs fine, but from the headset lights disappear at certain vertical angles. Here's an example:

https://user-images.githubusercontent.com/26148056/129972247-1c67d00e-fdc4-45e9-a4b1-bf1be8307dcf.mp4

If it's not an MRTK thing, any idea where I should look?

**Comment by provencher** [comment]
This is definitely something related to the MRTK standard shader. I'd recommend opening up a ticket with them. It seems to a problem with the proximity light portions of the shader there. My best guess is that it's a float precision issue on the Quest related to that shader.

**Comment by reeseras** [comment]
I opened an issue on their GitHub here: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10173#issue-974833072

**Comment by reeseras** [comment]
Turns out it was a unity shader issue. Upgrading to unity version 2019.4.29f1 fixed it.
